language: node_js
node_js:
- 6.5.0
before_install:
- openssl aes-256-cbc -K $encrypted_81984b3c73af_key -iv $encrypted_81984b3c73af_iv
  -in voteatx.pem.enc -out voteatx.pem -d
install:
- npm install -g sails
- npm install
- cd src && npm install
script:
- echo "normally you'd run 'npm test' or something"
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master